name: Setup
description: Setup the environment for the project

runs:
  using: composite

  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v6

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: "pnpm"
        registry-url: "https://registry.npmjs.org"

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
