name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  format:
    name: Format and lint
    uses: ./.github/workflows/format.yaml

  test:
    name: Test
    uses: ./.github/workflows/test.yaml
    permissions:
      contents: read
      pull-requests: write

  release:
    needs: [format, test]
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/setup

      - name: Create Release Pull Request or publish to npm
        uses: changesets/action@v1
        with:
          version: pnpm version-packages
          publish: pnpm release
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
